#!/bin/sh

old_dir="$1"
new_dir="$2"

if ! [ -d "$old_dir" ] || ! [ -d "$new_dir" ]; then
    exit 1
fi

for asset_dir in app/assets vendor/assets lib/assets; do
    if ! diff -qrN "$old_dir"/"$asset_dir" "$new_dir"/"$asset_dir"; then
        exit $?
    fi
done

exit 0
